core:
  - name: Apache Mesos
    class: mesos
    icon-label-first: M
    icon-label-last: s
    icon-class: mesos
    icon-style: color
    download-url: /downloads/details/index.html#apache-mesos
    older-download-url: /downloads/details/index.html#apache-mesos
    current-version: 0.21.0
    description: "Mesos makes it easy to develop distributed systems."
  - name: Marathon
    class: marathon
    icon-label-first: M
    icon-label-last: a
    icon-class: marathon
    icon-style: color
    download-url: /downloads/details/index.html#marathon
    older-download-url: /downloads/details/index.html#marathon
    current-version: 0.7.5
    description: "Marathon is a private PaaS built on Mesos."
  - name: Chronos
    class: chronos
    icon-label-first: C
    icon-label-last: h
    icon-class: chronos
    icon-style: white
    download-url: /downloads/details/index.html#chronos
    older-download-url: /downloads/details/index.html#chronos
    current-version: 2.1.0
    description: "Chronos is a distributed job scheduler."
community:
  - name: Apache Hadoop
    class: hadoop
    icon-label-first: H
    icon-label-last: a
    icon-class: hadoop
    icon-style: white
    download-url: http://hadoop.apache.org/
    older-download-url:
    current-version: 2.6.0
    description: "Distribute MapReduce jobs efficiently across a cluster."
  - name: Apache Spark
    class: spark
    icon-label-first: S
    icon-label-last: p
    icon-class: spark
    icon-style: white
    download-url: http://spark.incubator.apache.org/
    older-download-url:
    current-version: 1.1.1
    description: "Fast system which makes parallel jobs easy to write."
  - name: Apache Storm
    class: storm
    icon-label-first: S
    icon-label-last: t
    icon-class: storm
    icon-style: white
    download-url: http://storm.incubator.apache.org/
    older-download-url:
    current-version: 0.9.3
    description: "Distributed realtime computation system."
  - name: Apache Aurora
    class: aurora
    icon-label-first: A
    icon-label-last: u
    icon-class: aurora
    icon-style: white
    download-url: https://aurora.apache.org/
    older-download-url:
    current-version: 0.6.0
    description: "Service scheduler that runs on top of Mesos."
  - name: SSSP
    class: sssp
    icon-label-first: S
    icon-label-last: s
    icon-class:
    icon-style:
    download-url: https://github.com/mesosphere/sssp
    older-download-url:
    current-version: 0.0.1
    description: "A white-label &quot;Megaupload&quot; for storing and sharing files in S3."
  - name: Cray Chapel
    class: cray-chapel
    icon-label-first: C
    icon-label-last: c
    icon-class:
    icon-style:
    download-url: https://github.com/nqn/mesos-chapel
    older-download-url:
    current-version: 0.0.1
    description: "The Chapel Mesos scheduler lets you run Chapel programs on Mesos."
  - name: Exelixi
    class: exelixi
    icon-label-first: E
    icon-label-last: x
    icon-class:
    icon-style:
    download-url: https://github.com/mesosphere/exelixi
    older-download-url:
    current-version: 0.0.1
    description: "Exelixi is a distributed framework for running genetic algorithms."
  - name: Dpark
    class: dpark
    icon-label-first: D
    icon-label-last: p
    icon-class:
    icon-style:
    download-url: https://github.com/douban/dpark
    older-download-url:
    current-version: 0.1
    description: "Python clone of Spark."
  - name: MPI
    class: mpi
    icon-label-first: M
    icon-label-last: p
    icon-class:
    icon-style:
    download-url: https://github.com/mesosphere/mesos-hydra
    older-download-url:
    current-version: 0.1
    description: "A message-passing system."
  - name: Jenkins
    class: jenkins
    icon-label-first: J
    icon-label-last: k
    icon-class: jenkins
    icon-style: white
    download-url: https://wiki.jenkins-ci.org/display/JENKINS/Mesos+Plugin
    older-download-url:
    current-version: 0.5.0
    description: "Dynamically launch Jenkins workers."
  - name: Apache Cassandra
    class: cassandra
    icon-label-first: C
    icon-label-last: a
    icon-class: cassandra
    icon-style: white
    download-url: https://github.com/mesosphere/cassandra-mesos
    older-download-url:
    current-version: 0.1
    description: "A distributed database running on top of Mesos."
  - name: Hypertable
    class: hypertable
    icon-label-first: H
    icon-label-last: t
    icon-class:
    icon-style:
    download-url: https://code.google.com/p/hypertable/wiki/Mesos
    older-download-url:
    current-version: 0.9.8.4
    description: "A distributed storage system."
